# Generated by Django 4.1 on 2022-10-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorietracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calorie',
            name='calorie',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
