# Generated by Django 4.1 on 2022-10-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorietracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calorietracker',
            name='description',
            field=models.TextField(),
        ),
    ]
