# Generated by Django 4.1 on 2022-10-27 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorietracker', '0002_alter_calorie_calorie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calorie',
            options={'ordering': ['-date']},
        ),
    ]
