# Generated by Django 4.1 on 2022-10-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorietracker', '0003_alter_calorie_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calorie',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
