# Generated by Django 4.1 on 2022-10-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorietracker', '0004_alter_calorie_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='calorie',
            name='time',
            field=models.CharField(default='', max_length=300),
        ),
    ]
