# Generated by Django 4.1 on 2022-10-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodrecipe",
            name="author_name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
