# Generated by Django 4.1 on 2022-10-21 11:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PenggalanganDana',
            new_name='Donatee',
        ),
    ]
