# Generated by Django 4.1 on 2022-10-21 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_rename_penggalangandana_donatee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donatee',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='donatee',
            old_name='author',
            new_name='opener',
        ),
    ]
