# Generated by Django 4.1 on 2022-10-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_rename_title_donatee_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatee',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
