# Generated by Django 4.1 on 2022-10-25 14:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donation', '0004_alter_donatee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatee',
            name='amountNeeded',
            field=models.IntegerField(default=100000, validators=[django.core.validators.MinValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='donatee',
            name='opener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
