# Generated by Django 4.1 on 2022-10-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodsharing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharing',
            options={'ordering': ['-update_date']},
        ),
    ]
