# Generated by Django 4.1 on 2022-10-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsharing', '0003_sharing_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharing',
            name='location',
            field=models.TextField(),
        ),
    ]
