# Generated by Django 4.1 on 2022-10-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsharing', '0004_alter_sharing_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharing',
            name='img',
            field=models.URLField(blank=True, default='https://st4.depositphotos.com/14953852/24787/v/600/depositphotos_247872612-stock-illustration-no-image-available-icon-vector.jpg', max_length=500),
        ),
    ]
