# Generated by Django 4.1 on 2022-10-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsharing', '0005_alter_sharing_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharing',
            name='img',
            field=models.URLField(),
        ),
    ]
