# Generated by Django 4.1 on 2022-10-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='profile_pict_url',
            field=models.URLField(blank=True),
        ),
    ]
