# Generated by Django 4.1 on 2022-10-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_appuser_is_user_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='time_sent',
            field=models.DateTimeField(),
        ),
    ]
