# Generated by Django 4.1 on 2022-10-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_appuser_is_user_alter_message_time_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time_sent',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
